### ISSUE TITLE
accessing acquisition tiles using pylibCZIrw 

### ISSUE THREAD

**Issue by marius10p** [ZEISS/pylibczirw#10]
**Describe the bug**
Cannot access more than one tile using pylibCZIrw. The "V" parameter for the "plane" input contains the correct number of tiles, but only V = 0 returns a non-zero tile. I could not find information about this in the notebook tutorial. I installed pylibCZIrw from pip yesterday. 

```
print(czidoc.total_bounding_box)

{'T': (0, 1), 'Z': (0, 1716), 'C': (0, 2), 'R': (0, 1), 'I': (0, 1), 'H': (0, 1), 
'V': (0, 12), 'B': (0, 1), 'X': (0, 1920), 'Y': (0, 1920)}
```

**To Reproduce**
1. `X = czidoc.read(plane={"T": 0, "Z": 0, "C": 0, "V":0}, roi=(0, 0,1920, 1920))`
2. `Y = czidoc.read(plane={"T": 0, "Z": 0, "C": 0, "V":1}, roi=(0, 0,1920, 1920))`
3. X contains data from tile 0, Y contains only zeros. 

**Desktop (please complete the following information):**
 - Ubuntu 20.04 LTS
 - python
 - pylibCZIrw 4.1.1

**Comment by sebi06** [comment]
Hi @marius10p 

the "V" dimension is not for tiles (M-Dimension) but illumination planes. Here are the dimensions:

 Information official CZI Dimension Characters:
 "X":"Width"        : width of image [pixel]
 "Y":"Height"       : height of image [pixel]
 "C":"Channel"      : number of channels
 "Z":"Slice"         : number of z-planes
 "T":"Time"         : number of time points
 "R":"Rotation" 
 "S":"Scene"          : contiguous regions of interest in a mosaic image
 "I":"Illumination" : SPIM direction for LightSheet
 "B":"Block"          : acquisition block (legacy)
 "M":"Mosaic"      : index of tile for compositing a scene
 "H":"Phase"        : e.g. Airy detector fibers
 "V":"View"          : e.g. for SPIM

So what you are looking for is the "M"  dimension. But the current API we provide is a "2D Plane-based API" which does not expose the concept of "tiles" to the user (see also: [pylibCZIrw](https://pypi.org/project/pylibCZIrw/).

_"At the moment, pylibCZIrw completely abstracts away the subblock concept, both in the reading and in the writing APIs."_

So right now pylibCZIrw does not allow you to read "acquisition tiles", but only regions from a 2D plane. What you ask for makes sense and would be a new feature. May I ask what the exact use case is?

**Comment by marius10p** [comment]
Thanks for the explanation, much appreciated. I have acquisitions of 3x4 or  4x4 tiles and I can only get the data out from the top left tile. Is there a way to get the rest of the data out using the current API? It's possible that I just don't understand how scenes work.

**Comment by zeissmicroscopy** [comment]
Hi @marius10p 

You can get all tiles  at once as one 2D plane if you just leave out the ROI parameter I think.

Scenes are just "tags" for TileRegions and positions. So if you have 2 TileRegions of any size that will give you to scenes, but the "S" dimension is not really an orthogonal dimension like "T" or "Z".

Or image a wellplate with 96 wells where you add 2 positions per well --> 192 scenes

![image](https://github.com/ZEISS/pylibczirw/assets/29776849/0e7a5428-d505-4953-ae71-6760fd9ca61d)

**Comment by marius10p** [comment]
Thanks @zeissmicroscopy. If I leave out the roi parameter, I still only get a single tile, 1920x1920x1. I have tried extending the roi region beyond 1920x1920, but the rest comes out black.

**Comment by zeissmicroscopy** [comment]
HI @marius10p

ok, can you share the CZI somewhere? Was it acquired with ZEN Black?

**Comment by marius10p** [comment]
[here](https://drive.google.com/file/d/1wWXt23VG5olm1HTbLYgeVT91Mg7hRy0N/view?usp=sharing) is a substack of 1x3 tiles. Thanks for looking into this.

**Comment by sebi06** [comment]
Hi @marius10p 

I check the file you send me that this does not contain any tile (no M-Index) but 3 views (V-Index)

{'T': (0, 1), 'Z': (0, 51), 'C': (0, 2), 'R': (0, 1), 'I': (0, 1), 'H': (0, 1), 'V': (0, 3), 'B': (0, 1), 'X': (0, 1920), 'Y': (0, 1920)}

Therefore using the "roi" beyond 1920 x 1920 does not make sense. I think the issue is that you are using the old ZEN Black, which not really writing "official" CZI according to the specs for pylibCZIrw.

So what you know as tiles is treated the the V-Dimension in pylibCZIrw and therefore cannot be addressed with the "roi" parameter.

![image](https://github.com/ZEISS/pylibczirw/assets/3833249/48efb1ab-94c9-45a2-b4c7-f16534bc95bf)

**Comment by marius10p** [comment]
Thanks, yes I had noticed that, but I also cannot access the data using different V values. I get all zeros when V>0.

**Comment by marius10p** [comment]
Also, I confirmed with our imaging core that we are in fact running the latest 3.1 version of Zen black (like I said above), and we're only 1 or 2 "hotfixes" behind.

**Comment by sebi06** [comment]
meanwhile I think this really might be a bug inside pylibCZIrw, because I can get it to work with aicslibczi, which is also based on our libCZI.

```python
from aicspylibczi import CziFile
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
from pylibCZIrw import czi as pyczi

filepath = r"F:\Downloads\Gland_1x_3substack.czi"

# read via aicspylibCZI
czi = CziFile(filepath)

# Get the shape of the data, the coordinate pairs are (start index, size)
print(f"aicspylibCZI - Dimensions: {czi.get_dims_shape()}")

# Load the image slice I want from the file
img1_v0, shp = czi.read_image(Z=13, C=0, V=0)
img1_v1, shp = czi.read_image(Z=13, C=0, V=1)

# read via pylibCZIrw
with pyczi.open_czi(filepath) as czidoc:

    # get the image dimensions as a dictionary, where the key identifies the dimension
    print(f"pylibCZIrw - TotalBoundingBox: {czidoc.total_bounding_box}")

    img2_v0 = czidoc.read(plane={"Z": 13, "C": 0, "V": 0})
    img2_v1 = czidoc.read(plane={"Z": 13, "C": 0, "V": 1})


# show the 2D image plane
fig, ax = plt.subplots(2, 2, figsize=(12, 12))
ax[0, 0].imshow(
    np.squeeze(img1_v0), cmap=cm.inferno, vmin=img1_v0.min(), vmax=img1_v0.max()
)
ax[0, 1].imshow(
    img2_v0[..., 0], cmap=cm.inferno, vmin=img2_v0.min(), vmax=img2_v0.max()
)
ax[0, 0].set_title("Z=13, C=0, V=0 by aicspylibczi")
ax[0, 1].set_title("Z=13, C=0, V=0 by pylibczirw")
ax[1, 0].imshow(
    np.squeeze(img1_v1), cmap=cm.inferno, vmin=img1_v1.min(), vmax=img1_v1.max()
)
ax[1, 1].imshow(
    img2_v1[..., 0], cmap=cm.inferno, vmin=img2_v1.min(), vmax=img2_v1.max()
)
ax[1, 0].set_title("Z=13, C=0, V=1 by aicspylibczi")
ax[1, 1].set_title("Z=13, C=0, V=1 by pylibczirw")
plt.show()
```
gives me this:

![image](https://github.com/ZEISS/pylibczirw/assets/3833249/d2268e97-b6d4-4cab-99de-059b087131e8)

**Comment by ptahmose** [comment]
My analysis of this issue:

* The seems to be no problem when using CZICmd. E.g. this gives the expected result
`CZIcmd.exe -s n:\Gland_1x_3substack.czi -c SingleChannelScalingTileAccessor -p "V1Z13C0" -r "rel(0,0,1920,1920)" -o v1`
* Running [CZICheck](https://github.com/ZEISS/czicheck) on the file gives the following result
![image](https://github.com/ZEISS/pylibczirw/assets/4881321/3bd35806-3870-425c-a102-a1205fb95418)
This gives an indication of what the problem here is - it's the fact that the dimensions of the coordinates of the subblocks differ (or are inconsistent). Running `CZIcmd.exe -s n:\Gland_1x_3substack.czi -c PrintInformation -i AllSubBlocks` confirms this - for the subblocks with V=0 we have a B-dimension, but not for those with V<>0:
![image](https://github.com/ZEISS/pylibczirw/assets/4881321/ca9be70c-9280-4da6-a7a0-a0bb0805829a)

So, the problem here seems to be - the plane-coordinate that pylibczirw creates is "...B0" (i.e. requiring a valid B-dimension, with value 0), but for whatever reason - there is no B-dimension with all subblocks with V<>0. Again, this can be verified with CZICmd, where when giving a B-coordinate, we get an empty output (for V<>0). CZICheck considers the CZI as "not well-formed", and so do I.

To work around this issue - what I tried was to modify the plane-coordinate string which gets passed to libCZI to **not** include a coordinate for 'B'. This can be done by modifying [this line](https://github.com/ptahmose/zeiss-pylibczirw/blob/a9ece05c34471e4049cf3d46212f8f2085b5e5ed/pylibCZIrw/czi.py#L654) to something like
![image](https://github.com/ZEISS/pylibczirw/assets/4881321/10ee3db1-d40f-4f11-8755-ff3fb947cf20)
With this modification, the outcome of [above code](https://github.com/ZEISS/pylibczirw/issues/10#issuecomment-2200272999) seems as expected and correct:
![image](https://github.com/ZEISS/pylibczirw/assets/4881321/e2a5ae73-49fe-4e96-8986-fb4b48c61c19)

**Comment by ptahmose** [comment]
...what also happens to solve the issue here is this change
![image](https://github.com/ZEISS/pylibczirw/assets/4881321/213f1376-4db8-4f34-8744-d09a99d8e702)

The reasoning here is - there shouldn't be a necessity to give coordinate for a dimension for which the size is 1.
